apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-test
spec:
  template:
    spec:
      containers:
        - name: rollouts-test
          image: argoproj/rollouts-demo:green
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP      

