apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-test
spec:
  template:
    spec:
      containers:
        - name: app
          image: argoproj/rollouts-demo:yellow
          ports:
          - name: http
            containerPort: 80
            protocol: TCP      
---
apiVersion: gateway.networking.istio.io/v1            
kind: Gateway
metadata:
  name: ‎istio-rollout-gateway‎
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*.istio-rollout.local"
    - istio-rollout.local
    port:
      name: http
      number: 80
      protocol: HTTP
