apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-rollout-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - "istio-rollout.local"  
    - port:  
        name: https
        number: 443
        protocol: HTTPS        
      hosts:
        - "istio-rollout.local"       
      tls:
        mode: SIMPLE
        credentialName: example-credential
