apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-test
spec:
  selector:
    matchLabels:
      app: rollouts-test
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: rollouts-test
    spec:
      containers:
        - name: rollouts-test
          image: nginx:stable
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP          
  strategy:
    canary:
      canaryService: canary-svc  # required
      stableService: stable-svc  # required
      trafficRouting:
        nginx:
          stableIngress: virtual-service-demo-1
      steps:
      - setWeight: 5
      - pause:
          duration: 10m
