apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-test-1
spec:
  selector:
    matchLabels:
      app: rollouts-test-1
  template:
    metadata:
      labels:
        app: rollouts-test-1
    spec:
      containers:
        - name: app
          image: argoproj/rollouts-demo:blue
  strategy:
    canary:
      canaryService: canary-svc  # required
      stableService: stable-svc  # required
      trafficRouting:
        istio:
          virtualService:
            name: rollout-vsvc   # required
            routes:
            - primary            # optional if there is a single route in VirtualService, required otherwise
      steps:
      - setWeight: 5
      - pause:
          duration: 10m
