apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-test
spec:
  selector:
    matchLabels:
      app: rollouts-test
  template:
    metadata:
      labels:
        app: rollouts-test
    spec:
      containers:
        - name: app
          image: argoproj/rollouts-demo:blue
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP          
  strategy:
    canary:
      canaryService: canary-svc  # required
      stableService: stable-svc  # required
      trafficRouting:
        nginx:
          stableIngress: rollouts-test-stable
      steps:
      - setWeight: 5
      - pause:
          duration: 10m
