apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: rollout-vsvc
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - istio-rollout.local
  http:
  - name: primary        # referenced in canary.trafficRouting.istio.virtualService.routes
    route:
    - destination:
        host: stable-svc.default.svc.cluster.local # referenced in canary.stableService
      weight: 100
    - destination:
        host: canary-svc.default.svc.cluster.local # referenced in canary.canaryService
      weight: 0
